title: Git Commit Message Template
description: >-
  Git commit message template in English, based on Conventional Commits,
  with a guide and best practices.
theme: jekyll-theme-cayman
show_downloads: true
