blank_issues_enabled: true
contact_links:
  - name: Community Discussions
    url: "https://github.com/brayandiazc/gitmessage-template-en/discussions"
    about: Join the discussions to ask general questions
